name: Warera Tracker

on:
  workflow_dispatch:   # 👈 ESTO HABILITA EL BOTÓN
  schedule:
    - cron: "0 */12 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install requests firebase-admin

      - run: python tracker.py
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
